/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/new-robot-flipped-screen.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Robot base"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_1.geometry}
        material={materials["Robot second"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_2.geometry}
        material={materials["Robot third"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_3.geometry}
        material={materials.Black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.aboutMeButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.innovationButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.volunteeringButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.contactButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.industryButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PatentsButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BackButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, 1.17]}
        scale={1.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PublicationsButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, -11.26]}
        scale={[1, 1, 1.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ConferencesButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, -19.43]}
        scale={[1, 1, 1.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ResearchButton.geometry}
        material={materials.transparent}
        position={[1.31, 0, -23.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials.main_screen}
        position={[1.31, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/new-robot-flipped-screen.glb");
